services:
  azure-tts:
    image: ghcr.io/genzj/azure-tts:latest
    env_file:
      - .env
    # volumes:
    #   - .:/input  # Only needed to mount a custom deployment-input.json.template
    restart: "no"
    # ports:
    #   - 80
