services:
  azure-tts:
    build: .
    env_file:
      - .env
    # volumes:
    #   - .:/input  # Only needed to mount a custom deployment-input.json.template
    restart: "no"
    ports:
      - "9980:80"